@startuml
class Controller {
    + Controller()
    + AddInputCommand(command:InputCommands) : void
    + Stop() : void
}
Controller --> "LightRgbwEffect" ILightRgbwEffect
Controller --> "Communicator" ICommunicator
@enduml
