name: Generate UML Diagrams

on:
  push:
    branches:
      - master

jobs:
  generate_uml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7'  # or the version you are using

      - name: Install PlantUML
        run: |
          sudo apt-get install -y graphviz
          wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Generate UML Diagrams
        run: |
          dotnet build
          java -jar plantuml.jar -r **/*.cs
        working-directory: ${{ github.workspace }}
